[package]
name = "atoms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.20"
wasm-bindgen = "0.2.76"
web-sys = "0.3"
