name: pr_check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        profile: minimal
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'
    - name: Install Yarn
      run: npm install -g yarn
    - name: Build js
      run: esbuild js/index.ts --bundle --outdir=assets --target=es2015 --minify
    - name: Build css
      run: tailwindcss -i tailwind.css -o assets/index.css --minify
    - name: Build rust
      run: trunk build
    - name: Run tests
      run: cargo test --verbose
